// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: helios/v1/admin.proto

package heliosv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_helios_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helios_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_helios_v1_admin_proto_rawDescGZIP(), []int{0}
}

type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This node's own Raft ID.
	NodeId int64 `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// "follower", "candidate", or "leader" -- raft.State.String()'s own
	// three values, spelled as a string rather than a proto enum, since
	// this is a human-facing status report a caller displays, not a wire
	// value another program branches its own logic on the way
	// Consistency's own enum is.
	RaftState string `protobuf:"bytes,2,opt,name=raft_state,json=raftState,proto3" json:"raft_state,omitempty"`
	Term      int64  `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	// The peer ID this node currently believes leads, or -1 if unknown.
	// The identical "hint, not authority" meaning NotLeaderDetail.leader_id
	// (errors.proto, F-2) already carries.
	LeaderId    int64 `protobuf:"varint,4,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	CommitIndex int64 `protobuf:"varint,5,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	LastApplied int64 `protobuf:"varint,6,opt,name=last_applied,json=lastApplied,proto3" json:"last_applied,omitempty"`
	// How many entries this node currently holds in memory, INCLUDING
	// the one leading placeholder entry every Raft node keeps even
	// before its first real submission. log_length - 1 is the count of
	// real, submitted entries currently retained.
	LogLength int64 `protobuf:"varint,7,opt,name=log_length,json=logLength,proto3" json:"log_length,omitempty"`
	// 0, 0 if this node has never taken or installed a snapshot.
	SnapshotIndex int64 `protobuf:"varint,8,opt,name=snapshot_index,json=snapshotIndex,proto3" json:"snapshot_index,omitempty"`
	SnapshotTerm  int64 `protobuf:"varint,9,opt,name=snapshot_term,json=snapshotTerm,proto3" json:"snapshot_term,omitempty"`
	// The cluster membership this node currently believes is in force --
	// every voting member's own ID, this node included if it is one.
	Voters []int64 `protobuf:"varint,10,rep,packed,name=voters,proto3" json:"voters,omitempty"`
	// kvstore.Machine's own applied index -- distinct from last_applied
	// above (Raft's own bookkeeping of what it has handed over to the
	// state machine, not what the state machine has actually finished
	// applying). The two can differ briefly; both are reported rather
	// than assuming they always agree.
	MachineAppliedIndex int64 `protobuf:"varint,11,opt,name=machine_applied_index,json=machineAppliedIndex,proto3" json:"machine_applied_index,omitempty"`
	// kvstore.Machine.Fault() -- empty if healthy, otherwise the first
	// fault this Machine has recorded, exactly as that method's own doc
	// describes it.
	Fault         string `protobuf:"bytes,12,opt,name=fault,proto3" json:"fault,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_helios_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_helios_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_helios_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *StatusResponse) GetRaftState() string {
	if x != nil {
		return x.RaftState
	}
	return ""
}

func (x *StatusResponse) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *StatusResponse) GetLeaderId() int64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *StatusResponse) GetCommitIndex() int64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *StatusResponse) GetLastApplied() int64 {
	if x != nil {
		return x.LastApplied
	}
	return 0
}

func (x *StatusResponse) GetLogLength() int64 {
	if x != nil {
		return x.LogLength
	}
	return 0
}

func (x *StatusResponse) GetSnapshotIndex() int64 {
	if x != nil {
		return x.SnapshotIndex
	}
	return 0
}

func (x *StatusResponse) GetSnapshotTerm() int64 {
	if x != nil {
		return x.SnapshotTerm
	}
	return 0
}

func (x *StatusResponse) GetVoters() []int64 {
	if x != nil {
		return x.Voters
	}
	return nil
}

func (x *StatusResponse) GetMachineAppliedIndex() int64 {
	if x != nil {
		return x.MachineAppliedIndex
	}
	return 0
}

func (x *StatusResponse) GetFault() string {
	if x != nil {
		return x.Fault
	}
	return ""
}

var File_helios_v1_admin_proto protoreflect.FileDescriptor

const file_helios_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x15helios/v1/admin.proto\x12\thelios.v1\"\x0f\n" +
	"\rStatusRequest\"\x8c\x03\n" +
	"\x0eStatusResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\x12\x1d\n" +
	"\n" +
	"raft_state\x18\x02 \x01(\tR\traftState\x12\x12\n" +
	"\x04term\x18\x03 \x01(\x03R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x04 \x01(\x03R\bleaderId\x12!\n" +
	"\fcommit_index\x18\x05 \x01(\x03R\vcommitIndex\x12!\n" +
	"\flast_applied\x18\x06 \x01(\x03R\vlastApplied\x12\x1d\n" +
	"\n" +
	"log_length\x18\a \x01(\x03R\tlogLength\x12%\n" +
	"\x0esnapshot_index\x18\b \x01(\x03R\rsnapshotIndex\x12#\n" +
	"\rsnapshot_term\x18\t \x01(\x03R\fsnapshotTerm\x12\x16\n" +
	"\x06voters\x18\n" +
	" \x03(\x03R\x06voters\x122\n" +
	"\x15machine_applied_index\x18\v \x01(\x03R\x13machineAppliedIndex\x12\x14\n" +
	"\x05fault\x18\f \x01(\tR\x05fault2L\n" +
	"\vHeliosAdmin\x12=\n" +
	"\x06Status\x12\x18.helios.v1.StatusRequest\x1a\x19.helios.v1.StatusResponseB4Z2github.com/ekushal02/helios/api/helios/v1;heliosv1b\x06proto3"

var (
	file_helios_v1_admin_proto_rawDescOnce sync.Once
	file_helios_v1_admin_proto_rawDescData []byte
)

func file_helios_v1_admin_proto_rawDescGZIP() []byte {
	file_helios_v1_admin_proto_rawDescOnce.Do(func() {
		file_helios_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_helios_v1_admin_proto_rawDesc), len(file_helios_v1_admin_proto_rawDesc)))
	})
	return file_helios_v1_admin_proto_rawDescData
}

var file_helios_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_helios_v1_admin_proto_goTypes = []any{
	(*StatusRequest)(nil),  // 0: helios.v1.StatusRequest
	(*StatusResponse)(nil), // 1: helios.v1.StatusResponse
}
var file_helios_v1_admin_proto_depIdxs = []int32{
	0, // 0: helios.v1.HeliosAdmin.Status:input_type -> helios.v1.StatusRequest
	1, // 1: helios.v1.HeliosAdmin.Status:output_type -> helios.v1.StatusResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_helios_v1_admin_proto_init() }
func file_helios_v1_admin_proto_init() {
	if File_helios_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_helios_v1_admin_proto_rawDesc), len(file_helios_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_helios_v1_admin_proto_goTypes,
		DependencyIndexes: file_helios_v1_admin_proto_depIdxs,
		MessageInfos:      file_helios_v1_admin_proto_msgTypes,
	}.Build()
	File_helios_v1_admin_proto = out.File
	file_helios_v1_admin_proto_goTypes = nil
	file_helios_v1_admin_proto_depIdxs = nil
}
