// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: helios/v1/admin.proto

package heliosv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HeliosAdmin_Status_FullMethodName = "/helios.v1.HeliosAdmin/Status"
)

// HeliosAdminClient is the client API for HeliosAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HeliosAdmin is a deliberately separate service from Helios
// (helios.proto) -- introspection and operations concerns, not the
// client-facing data-plane reads and writes that service exists for.
// Kept in its own file and its own service block for the identical
// reason errors.proto (F-2) was kept separate from helios.proto: this
// is additive tooling around the cluster, not a change to the
// client-facing API surface F-1 already froze.
type HeliosAdminClient interface {
	// Status reports THIS node's own point-in-time view of its Raft and
	// storage state. Deliberately NOT leader-gated, unlike every
	// data-plane RPC in helios.proto -- see internal/server's own doc on
	// Server.Status for the full reasoning (the same shape Watch's own
	// F-7 not-leader-gated decision already argued): a follower
	// correctly reporting "I am a follower, term 3" is exactly what an
	// admin caller inspecting that node wants, not something to reject.
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type heliosAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewHeliosAdminClient(cc grpc.ClientConnInterface) HeliosAdminClient {
	return &heliosAdminClient{cc}
}

func (c *heliosAdminClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, HeliosAdmin_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HeliosAdminServer is the server API for HeliosAdmin service.
// All implementations must embed UnimplementedHeliosAdminServer
// for forward compatibility.
//
// HeliosAdmin is a deliberately separate service from Helios
// (helios.proto) -- introspection and operations concerns, not the
// client-facing data-plane reads and writes that service exists for.
// Kept in its own file and its own service block for the identical
// reason errors.proto (F-2) was kept separate from helios.proto: this
// is additive tooling around the cluster, not a change to the
// client-facing API surface F-1 already froze.
type HeliosAdminServer interface {
	// Status reports THIS node's own point-in-time view of its Raft and
	// storage state. Deliberately NOT leader-gated, unlike every
	// data-plane RPC in helios.proto -- see internal/server's own doc on
	// Server.Status for the full reasoning (the same shape Watch's own
	// F-7 not-leader-gated decision already argued): a follower
	// correctly reporting "I am a follower, term 3" is exactly what an
	// admin caller inspecting that node wants, not something to reject.
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedHeliosAdminServer()
}

// UnimplementedHeliosAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHeliosAdminServer struct{}

func (UnimplementedHeliosAdminServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedHeliosAdminServer) mustEmbedUnimplementedHeliosAdminServer() {}
func (UnimplementedHeliosAdminServer) testEmbeddedByValue()                     {}

// UnsafeHeliosAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HeliosAdminServer will
// result in compilation errors.
type UnsafeHeliosAdminServer interface {
	mustEmbedUnimplementedHeliosAdminServer()
}

func RegisterHeliosAdminServer(s grpc.ServiceRegistrar, srv HeliosAdminServer) {
	// If the following call panics, it indicates UnimplementedHeliosAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HeliosAdmin_ServiceDesc, srv)
}

func _HeliosAdmin_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeliosAdminServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HeliosAdmin_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeliosAdminServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HeliosAdmin_ServiceDesc is the grpc.ServiceDesc for HeliosAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HeliosAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helios.v1.HeliosAdmin",
	HandlerType: (*HeliosAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _HeliosAdmin_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helios/v1/admin.proto",
}
