// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: helios/v1/errors.proto

package heliosv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NotLeaderDetail is what helios.proto's own service comment already
// promised: "F-2 attaches leader-hint metadata to the gRPC status
// (details) rather than a field on every response." Not an RPC request
// or response -- attached to a codes.Unavailable status via
// google.golang.org/grpc/status's WithDetails, so a client library
// (F-3) can retrieve it programmatically (status.FromError, then
// st.Details()) instead of parsing an error string. A separate file
// from helios.proto, deliberately: this is additive tooling around the
// error path, not a change to the RPC surface F-1 already froze.
type NotLeaderDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The peer ID this node currently believes leads, or -1 if unknown
	// (raft.None -- no election has completed yet, or this node's belief
	// was just reset by stepping down or becoming a candidate).
	//
	// DELIBERATELY NOT AN ADDRESS. Resolving a peer ID to a dialable
	// network address needs a cluster address book, which does not exist
	// anywhere in this project yet -- internal/raft's own Transport has
	// never had a real network implementation (see cmd/helios's own doc).
	// That book belongs to whichever layer actually dials a peer, which
	// is the client library, not this node -- F-3 ("Go client library:
	// connect, discover the leader, retry with backoff on NotLeader") is
	// exactly where it's designed to live, not guessed at here.
	LeaderId      int64 `protobuf:"varint,1,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotLeaderDetail) Reset() {
	*x = NotLeaderDetail{}
	mi := &file_helios_v1_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotLeaderDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotLeaderDetail) ProtoMessage() {}

func (x *NotLeaderDetail) ProtoReflect() protoreflect.Message {
	mi := &file_helios_v1_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotLeaderDetail.ProtoReflect.Descriptor instead.
func (*NotLeaderDetail) Descriptor() ([]byte, []int) {
	return file_helios_v1_errors_proto_rawDescGZIP(), []int{0}
}

func (x *NotLeaderDetail) GetLeaderId() int64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

var File_helios_v1_errors_proto protoreflect.FileDescriptor

const file_helios_v1_errors_proto_rawDesc = "" +
	"\n" +
	"\x16helios/v1/errors.proto\x12\thelios.v1\".\n" +
	"\x0fNotLeaderDetail\x12\x1b\n" +
	"\tleader_id\x18\x01 \x01(\x03R\bleaderIdB4Z2github.com/ekushal02/helios/api/helios/v1;heliosv1b\x06proto3"

var (
	file_helios_v1_errors_proto_rawDescOnce sync.Once
	file_helios_v1_errors_proto_rawDescData []byte
)

func file_helios_v1_errors_proto_rawDescGZIP() []byte {
	file_helios_v1_errors_proto_rawDescOnce.Do(func() {
		file_helios_v1_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_helios_v1_errors_proto_rawDesc), len(file_helios_v1_errors_proto_rawDesc)))
	})
	return file_helios_v1_errors_proto_rawDescData
}

var file_helios_v1_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_helios_v1_errors_proto_goTypes = []any{
	(*NotLeaderDetail)(nil), // 0: helios.v1.NotLeaderDetail
}
var file_helios_v1_errors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_helios_v1_errors_proto_init() }
func file_helios_v1_errors_proto_init() {
	if File_helios_v1_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_helios_v1_errors_proto_rawDesc), len(file_helios_v1_errors_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_helios_v1_errors_proto_goTypes,
		DependencyIndexes: file_helios_v1_errors_proto_depIdxs,
		MessageInfos:      file_helios_v1_errors_proto_msgTypes,
	}.Build()
	File_helios_v1_errors_proto = out.File
	file_helios_v1_errors_proto_goTypes = nil
	file_helios_v1_errors_proto_depIdxs = nil
}
