// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: helios/v1/helios.proto

// package helios.v1 — the "v1" is load-bearing, not decorative: it's how we
// version the wire contract independently of the Go module. A breaking change
// to a request/response shape means a new "v1" -> "v2" package, not an edit
// in place, so old clients talking to a rolling-upgraded cluster don't
// silently misparse frames mid-deploy.

package heliosv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Consistency selects the read guarantee for a Get or Scan.
//
// The Raft layer already implements two read strategies (Phase C):
// a committed-index barrier read and a lease read bounded by a measured
// clock-skew assumption. This enum is what lets a client choose between
// them instead of the server silently picking one. CONSISTENCY_UNSPECIFIED
// resolves to CONSISTENCY_LINEARIZABLE server-side — the safe default is
// the expensive one, not the fast one, so a client that forgets to set this
// field gets correctness, not a surprise staleness bug.
type Consistency int32

const (
	Consistency_CONSISTENCY_UNSPECIFIED Consistency = 0
	// Linearizable: goes through the read-index/lease-read path. Every reader
	// sees every write that completed before the read started.
	Consistency_CONSISTENCY_LINEARIZABLE Consistency = 1
	// Stale: served from local state without a leader round trip. May not
	// reflect the most recent committed writes. Useful for read-heavy,
	// staleness-tolerant workloads (dashboards, metrics scraping).
	Consistency_CONSISTENCY_STALE Consistency = 2
)

// Enum value maps for Consistency.
var (
	Consistency_name = map[int32]string{
		0: "CONSISTENCY_UNSPECIFIED",
		1: "CONSISTENCY_LINEARIZABLE",
		2: "CONSISTENCY_STALE",
	}
	Consistency_value = map[string]int32{
		"CONSISTENCY_UNSPECIFIED":  0,
		"CONSISTENCY_LINEARIZABLE": 1,
		"CONSISTENCY_STALE":        2,
	}
)

func (x Consistency) Enum() *Consistency {
	p := new(Consistency)
	*p = x
	return p
}

func (x Consistency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Consistency) Descriptor() protoreflect.EnumDescriptor {
	return file_helios_v1_helios_proto_enumTypes[0].Descriptor()
}

func (Consistency) Type() protoreflect.EnumType {
	return &file_helios_v1_helios_proto_enumTypes[0]
}

func (x Consistency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Consistency.Descriptor instead.
func (Consistency) EnumDescriptor() ([]byte, []int) {
	return file_helios_v1_helios_proto_rawDescGZIP(), []int{0}
}

type WatchEvent_Type int32

const (
	WatchEvent_TYPE_UNSPECIFIED WatchEvent_Type = 0
	WatchEvent_PUT              WatchEvent_Type = 1
	WatchEvent_DELETE           WatchEvent_Type = 2
)

// Enum value maps for WatchEvent_Type.
var (
	WatchEvent_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "PUT",
		2: "DELETE",
	}
	WatchEvent_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"PUT":              1,
		"DELETE":           2,
	}
)

func (x WatchEvent_Type) Enum() *WatchEvent_Type {
	p := new(WatchEvent_Type)
	*p = x
	return p
}

func (x WatchEvent_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WatchEvent_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_helios_v1_helios_proto_enumTypes[1].Descriptor()
}

func (WatchEvent_Type) Type() protoreflect.EnumType {
	return &file_helios_v1_helios_proto_enumTypes[1]
}

func (x WatchEvent_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WatchEvent_Type.Descriptor instead.
func (WatchEvent_Type) EnumDescriptor() ([]byte, []int) {
	return file_helios_v1_helios_proto_rawDescGZIP(), []int{10, 0}
}

// Every KV response carries a "revision": the Raft log index at which that
// value was committed. It's a free, already-existing monotonic counter —
// we're not inventing a new versioning scheme, just exposing commitIndex/
// lastApplied (concepts already load-bearing inside internal/raft) at the
// API boundary. This is what a client-side watcher or a future MVCC layer
// would key off of.
type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Revision      int64                  `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_helios_v1_helios_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_helios_v1_helios_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_helios_v1_helios_proto_rawDescGZIP(), []int{0}
}

func (x *KeyValue) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KeyValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *KeyValue) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Consistency   Consistency            `protobuf:"varint,2,opt,name=consistency,proto3,enum=helios.v1.Consistency" json:"consistency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_helios_v1_helios_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helios_v1_helios_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_helios_v1_helios_proto_rawDescGZIP(), []int{1}
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *GetRequest) GetConsistency() Consistency {
	if x != nil {
		return x.Consistency
	}
	return Consistency_CONSISTENCY_UNSPECIFIED
}

type GetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Value []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// Proto3 can't distinguish "empty value" from "field not set", so a
	// missing key needs its own signal. `found` is that signal — check it
	// before trusting `value`, the same way a Go map's comma-ok idiom works.
	Found bool `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	// 0 when found == false. Otherwise the revision this value was written at.
	Revision      int64 `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_helios_v1_helios_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_helios_v1_helios_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_helios_v1_helios_proto_rawDescGZIP(), []int{2}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetResponse) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type PutRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// F-4: identifies this write for duplicate suppression across a
	// client's own retries. client_id = 0 means "no client session" --
	// the write is NOT deduplicated, the same behavior every PutRequest
	// had before this field existed. A real client_id is never 0 (see
	// client.Client's own doc on how it is generated); 0 is reserved
	// exactly so a caller not using this project's client library --
	// direct grpcurl, a future admin tool, anything constructing a raw
	// PutRequest -- keeps working unchanged rather than being forced to
	// either opt in or be rejected.
	ClientId uint64 `protobuf:"varint,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// Monotonically increasing per client_id, assigned once per LOGICAL
	// write and reused, unchanged, across every retry of that same write
	// -- never per RPC attempt. The state machine (internal/kvstore)
	// remembers the highest sequence_number it has applied for each
	// client_id; a request at or below that value is recognized as
	// already applied and is not applied again, even if it reaches a
	// different node or a different Raft term than the original did.
	SequenceNumber uint64 `protobuf:"varint,4,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_helios_v1_helios_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helios_v1_helios_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_helios_v1_helios_proto_rawDescGZIP(), []int{3}
}

func (x *PutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PutRequest) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *PutRequest) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

type PutResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The revision the write committed at. Lets a client that wants
	// read-your-writes pass this straight back in a later GetRequest's
	// consistency handling, without us needing a separate "read your own
	// write" mode.
	Revision      int64 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_helios_v1_helios_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_helios_v1_helios_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_helios_v1_helios_proto_rawDescGZIP(), []int{4}
}

func (x *PutResponse) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type DeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Identical contract to PutRequest's own fields of the same name (F-4)
	// -- see that message's doc. A delete is a write (§13.7's own
	// argument, all the way up to this, its client-facing surface), so it
	// needs the identical duplicate-suppression treatment a Put does, not
	// a different one.
	ClientId       uint64 `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	SequenceNumber uint64 `protobuf:"varint,3,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_helios_v1_helios_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helios_v1_helios_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_helios_v1_helios_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *DeleteRequest) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *DeleteRequest) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

type DeleteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the key existed immediately before this delete. Mirrors
	// GetResponse.found so callers reuse the same mental model instead of
	// inferring existence from a zero revision.
	Found         bool  `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Revision      int64 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_helios_v1_helios_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_helios_v1_helios_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_helios_v1_helios_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *DeleteResponse) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type ScanRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Inclusive lower bound. Empty means "from the beginning of the keyspace".
	StartKey []byte `protobuf:"bytes,1,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"`
	// Exclusive upper bound. Empty means "no upper bound".
	EndKey []byte `protobuf:"bytes,2,opt,name=end_key,json=endKey,proto3" json:"end_key,omitempty"`
	// Max pairs to return in this response. 0 lets the server pick a default
	// page size rather than the client guessing one.
	Limit int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// Opaque — set from the previous ScanResponse.next_page_token to
	// continue. Clients must not construct or parse this token themselves;
	// its internal encoding is a server implementation detail (F-6) that can
	// change without breaking this schema.
	PageToken     []byte      `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	Consistency   Consistency `protobuf:"varint,5,opt,name=consistency,proto3,enum=helios.v1.Consistency" json:"consistency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_helios_v1_helios_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helios_v1_helios_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_helios_v1_helios_proto_rawDescGZIP(), []int{7}
}

func (x *ScanRequest) GetStartKey() []byte {
	if x != nil {
		return x.StartKey
	}
	return nil
}

func (x *ScanRequest) GetEndKey() []byte {
	if x != nil {
		return x.EndKey
	}
	return nil
}

func (x *ScanRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ScanRequest) GetPageToken() []byte {
	if x != nil {
		return x.PageToken
	}
	return nil
}

func (x *ScanRequest) GetConsistency() Consistency {
	if x != nil {
		return x.Consistency
	}
	return Consistency_CONSISTENCY_UNSPECIFIED
}

type ScanResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Pairs []*KeyValue            `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
	// Empty when the scan is exhausted; non-empty means "call again with
	// this as page_token for the next page".
	NextPageToken []byte `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_helios_v1_helios_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_helios_v1_helios_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_helios_v1_helios_proto_rawDescGZIP(), []int{8}
}

func (x *ScanResponse) GetPairs() []*KeyValue {
	if x != nil {
		return x.Pairs
	}
	return nil
}

func (x *ScanResponse) GetNextPageToken() []byte {
	if x != nil {
		return x.NextPageToken
	}
	return nil
}

type WatchRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	KeyPrefix []byte                 `protobuf:"bytes,1,opt,name=key_prefix,json=keyPrefix,proto3" json:"key_prefix,omitempty"`
	// 0 means "start watching from now". A non-zero value replays committed
	// changes from that revision forward before switching to live delivery —
	// this is what lets a client resume a watch after a reconnect without
	// missing writes that happened during the gap.
	StartRevision int64 `protobuf:"varint,2,opt,name=start_revision,json=startRevision,proto3" json:"start_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_helios_v1_helios_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helios_v1_helios_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_helios_v1_helios_proto_rawDescGZIP(), []int{9}
}

func (x *WatchRequest) GetKeyPrefix() []byte {
	if x != nil {
		return x.KeyPrefix
	}
	return nil
}

func (x *WatchRequest) GetStartRevision() int64 {
	if x != nil {
		return x.StartRevision
	}
	return 0
}

type WatchEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  WatchEvent_Type        `protobuf:"varint,1,opt,name=type,proto3,enum=helios.v1.WatchEvent_Type" json:"type,omitempty"`
	Key   []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// Empty for DELETE events.
	Value         []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Revision      int64  `protobuf:"varint,4,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEvent) Reset() {
	*x = WatchEvent{}
	mi := &file_helios_v1_helios_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEvent) ProtoMessage() {}

func (x *WatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_helios_v1_helios_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEvent.ProtoReflect.Descriptor instead.
func (*WatchEvent) Descriptor() ([]byte, []int) {
	return file_helios_v1_helios_proto_rawDescGZIP(), []int{10}
}

func (x *WatchEvent) GetType() WatchEvent_Type {
	if x != nil {
		return x.Type
	}
	return WatchEvent_TYPE_UNSPECIFIED
}

func (x *WatchEvent) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *WatchEvent) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *WatchEvent) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type WatchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Batched rather than one event per message: under bursty writes this
	// cuts stream frames roughly in proportion to batch size, the same
	// amortization argument already measured for AppendEntries coalescing
	// in the Raft layer (DESIGN.md, replication coalescing).
	Events        []*WatchEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	mi := &file_helios_v1_helios_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_helios_v1_helios_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse.ProtoReflect.Descriptor instead.
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return file_helios_v1_helios_proto_rawDescGZIP(), []int{11}
}

func (x *WatchResponse) GetEvents() []*WatchEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_helios_v1_helios_proto protoreflect.FileDescriptor

const file_helios_v1_helios_proto_rawDesc = "" +
	"\n" +
	"\x16helios/v1/helios.proto\x12\thelios.v1\"N\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x03R\brevision\"X\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x128\n" +
	"\vconsistency\x18\x02 \x01(\x0e2\x16.helios.v1.ConsistencyR\vconsistency\"U\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x03R\brevision\"z\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\x04R\bclientId\x12'\n" +
	"\x0fsequence_number\x18\x04 \x01(\x04R\x0esequenceNumber\")\n" +
	"\vPutResponse\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x03R\brevision\"g\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\x04R\bclientId\x12'\n" +
	"\x0fsequence_number\x18\x03 \x01(\x04R\x0esequenceNumber\"B\n" +
	"\x0eDeleteResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x03R\brevision\"\xb2\x01\n" +
	"\vScanRequest\x12\x1b\n" +
	"\tstart_key\x18\x01 \x01(\fR\bstartKey\x12\x17\n" +
	"\aend_key\x18\x02 \x01(\fR\x06endKey\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\fR\tpageToken\x128\n" +
	"\vconsistency\x18\x05 \x01(\x0e2\x16.helios.v1.ConsistencyR\vconsistency\"a\n" +
	"\fScanResponse\x12)\n" +
	"\x05pairs\x18\x01 \x03(\v2\x13.helios.v1.KeyValueR\x05pairs\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\fR\rnextPageToken\"T\n" +
	"\fWatchRequest\x12\x1d\n" +
	"\n" +
	"key_prefix\x18\x01 \x01(\fR\tkeyPrefix\x12%\n" +
	"\x0estart_revision\x18\x02 \x01(\x03R\rstartRevision\"\xb3\x01\n" +
	"\n" +
	"WatchEvent\x12.\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.helios.v1.WatchEvent.TypeR\x04type\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\x03R\brevision\"1\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03PUT\x10\x01\x12\n" +
	"\n" +
	"\x06DELETE\x10\x02\">\n" +
	"\rWatchResponse\x12-\n" +
	"\x06events\x18\x01 \x03(\v2\x15.helios.v1.WatchEventR\x06events*_\n" +
	"\vConsistency\x12\x1b\n" +
	"\x17CONSISTENCY_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CONSISTENCY_LINEARIZABLE\x10\x01\x12\x15\n" +
	"\x11CONSISTENCY_STALE\x10\x022\xaa\x02\n" +
	"\x06Helios\x124\n" +
	"\x03Get\x12\x15.helios.v1.GetRequest\x1a\x16.helios.v1.GetResponse\x124\n" +
	"\x03Put\x12\x15.helios.v1.PutRequest\x1a\x16.helios.v1.PutResponse\x12=\n" +
	"\x06Delete\x12\x18.helios.v1.DeleteRequest\x1a\x19.helios.v1.DeleteResponse\x127\n" +
	"\x04Scan\x12\x16.helios.v1.ScanRequest\x1a\x17.helios.v1.ScanResponse\x12<\n" +
	"\x05Watch\x12\x17.helios.v1.WatchRequest\x1a\x18.helios.v1.WatchResponse0\x01B4Z2github.com/ekushal02/helios/api/helios/v1;heliosv1b\x06proto3"

var (
	file_helios_v1_helios_proto_rawDescOnce sync.Once
	file_helios_v1_helios_proto_rawDescData []byte
)

func file_helios_v1_helios_proto_rawDescGZIP() []byte {
	file_helios_v1_helios_proto_rawDescOnce.Do(func() {
		file_helios_v1_helios_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_helios_v1_helios_proto_rawDesc), len(file_helios_v1_helios_proto_rawDesc)))
	})
	return file_helios_v1_helios_proto_rawDescData
}

var file_helios_v1_helios_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_helios_v1_helios_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_helios_v1_helios_proto_goTypes = []any{
	(Consistency)(0),       // 0: helios.v1.Consistency
	(WatchEvent_Type)(0),   // 1: helios.v1.WatchEvent.Type
	(*KeyValue)(nil),       // 2: helios.v1.KeyValue
	(*GetRequest)(nil),     // 3: helios.v1.GetRequest
	(*GetResponse)(nil),    // 4: helios.v1.GetResponse
	(*PutRequest)(nil),     // 5: helios.v1.PutRequest
	(*PutResponse)(nil),    // 6: helios.v1.PutResponse
	(*DeleteRequest)(nil),  // 7: helios.v1.DeleteRequest
	(*DeleteResponse)(nil), // 8: helios.v1.DeleteResponse
	(*ScanRequest)(nil),    // 9: helios.v1.ScanRequest
	(*ScanResponse)(nil),   // 10: helios.v1.ScanResponse
	(*WatchRequest)(nil),   // 11: helios.v1.WatchRequest
	(*WatchEvent)(nil),     // 12: helios.v1.WatchEvent
	(*WatchResponse)(nil),  // 13: helios.v1.WatchResponse
}
var file_helios_v1_helios_proto_depIdxs = []int32{
	0,  // 0: helios.v1.GetRequest.consistency:type_name -> helios.v1.Consistency
	0,  // 1: helios.v1.ScanRequest.consistency:type_name -> helios.v1.Consistency
	2,  // 2: helios.v1.ScanResponse.pairs:type_name -> helios.v1.KeyValue
	1,  // 3: helios.v1.WatchEvent.type:type_name -> helios.v1.WatchEvent.Type
	12, // 4: helios.v1.WatchResponse.events:type_name -> helios.v1.WatchEvent
	3,  // 5: helios.v1.Helios.Get:input_type -> helios.v1.GetRequest
	5,  // 6: helios.v1.Helios.Put:input_type -> helios.v1.PutRequest
	7,  // 7: helios.v1.Helios.Delete:input_type -> helios.v1.DeleteRequest
	9,  // 8: helios.v1.Helios.Scan:input_type -> helios.v1.ScanRequest
	11, // 9: helios.v1.Helios.Watch:input_type -> helios.v1.WatchRequest
	4,  // 10: helios.v1.Helios.Get:output_type -> helios.v1.GetResponse
	6,  // 11: helios.v1.Helios.Put:output_type -> helios.v1.PutResponse
	8,  // 12: helios.v1.Helios.Delete:output_type -> helios.v1.DeleteResponse
	10, // 13: helios.v1.Helios.Scan:output_type -> helios.v1.ScanResponse
	13, // 14: helios.v1.Helios.Watch:output_type -> helios.v1.WatchResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_helios_v1_helios_proto_init() }
func file_helios_v1_helios_proto_init() {
	if File_helios_v1_helios_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_helios_v1_helios_proto_rawDesc), len(file_helios_v1_helios_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_helios_v1_helios_proto_goTypes,
		DependencyIndexes: file_helios_v1_helios_proto_depIdxs,
		EnumInfos:         file_helios_v1_helios_proto_enumTypes,
		MessageInfos:      file_helios_v1_helios_proto_msgTypes,
	}.Build()
	File_helios_v1_helios_proto = out.File
	file_helios_v1_helios_proto_goTypes = nil
	file_helios_v1_helios_proto_depIdxs = nil
}
